### ISSUE TITLE
Enabling redstone bugs via config makes your game crash whenever using redstone

### ISSUE THREAD

**Issue by LateSnowFox** [MMonkeyKiller/2.0-Rediscovered#2]
What the title says. It doesn't matter the probability, it just makes your game crash.

I have a theory that the game crashes as soon as a redstone bug spawn and is alive, as when I disabled the redstone bug config i saw that a silverfish has spawned.

**Comment by MMonkeyKiller** [comment]
Hello! Sorry to hear that. What version of the game are you using? Can you attach the crash log?

**Comment by LateSnowFox** [comment]
This may be the cause of my issue but I'm on 1.20.1. Everything else works perfectly fine though.
![uh ohhh](https://github.com/MMonkeyKiller/2.0-Rediscovered/assets/107361147/9f6077e8-34a3-46c2-b55e-c17d0866457c)

[crash-2024-06-25_13.47.19-client.txt](https://github.com/user-attachments/files/15970385/crash-2024-06-25_13.47.19-client.txt)

**Comment by MMonkeyKiller** [comment]
Fixed! Check the latest release 😉
